### PR TITLE
Pre-empt API continue breakage

### PR DESCRIPTION
**Pull request by maflcko**
Further fixes include:
- Decompiler cleanup (This decompiler behaved a bit too conservative)
- Update Wiki.java and WMFWiki.java to latest version and refactor code as necessary

### CODE REVIEW

**Comment by Rillke** [comment]
going to review this today

**Comment by Rillke** [comment]
I haven't tested actual uploading but it builds. Thanks for the work you've put into this.

**Comment by Rillke** [comment]
If you would like to have access to this repo, you might have but I'll have to poke people since it's part of Commonists now.

**Comment by dschwen** [comment]
@rillke you are a sysop for Communists on github. You should have enough permissions to not need to poke people :-)

**Comment by Rillke** [comment]
@dschwen Okay, I see now that I can invite to Sysops but not to Coders.

**Comment by maflcko** [comment]
@Rillke Thanks for the offer but I think peer review is better. ;) Usually, I break things instead of fixing them.

**Comment by Rillke** [comment]
@MarcoFalke You should have written that in your admin candidacy at Commons :dragon_face:

**Comment by maflcko** [comment]
@Rillke Blame the guy, who actually wrote it. :stuck_out_tongue: 

But if you want, go ahead and add me, I will try to be more cautious than in my own git repos.

**Comment by Rillke** [comment]
@MarcoFalke if you accepted the invitation to Commonists (and it looks like you did), you should have access to this repo.

**Comment by maflcko** [comment]
@Rillke , confirmed. So are you publishing the new Up-release?

**Comment by Rillke** [comment]
> So are you publishing the new Up-release?

I'll try to remember doing this tomorrow.

Anyone knows whether CI could do this for us (e.g. when pushing tags to git)?

**Comment by JeanFred** [comment]
> Anyone knows whether CI could do this for us (e.g. when pushing tags to git)?

@Rillke I can have a look on this − please open an issue and assign to me :)

**Comment by JeanFred** [comment]
(I’m not sure I completely get how GitHub permissions work. Seems like teams have only per-repo access − so the Coders team can only access repos that are added to it. That’s annoying. We could look into have separate teams per repo but at the same time I think we are all trust each others so there is not much point in having complex permissions setup I think.)

**Pull request merged**
